FROM python:3.12-slim

RUN useradd -m appuser

WORKDIR /app 

# INSTALL REQU
COPY requirments.txt .
RUN pip install --no-cache-dir -r requirments.txt


# COPY CODE
COPY app ./app

# CHANGE USER
USER appuser

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
